# Generated by Django 2.2.11 on 2020-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200317_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_story',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
