# Generated by Django 2.2.11 on 2020-03-23 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200322_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
